#!/bin/bash

run_cmd_debug=1

site_test="-t"
site_run="-r"
update="-u"
WORKSPACE=$(pwd)
base_script=${0}

function exit_fn()
{
    echo "Exiting ..."
    clean_old_logs
    rm_proff_temp
}

EXITFUN="exit_fn"

if [ -f _toolScripts/bash_func ]; then
        . _toolScripts/bash_func
else
        echo "Error on _toolScripts/bash_func ..."
fi


### MAIN ###
link_draft
if [ "$1" == "$update" ]
then
    git_sub_update
    clean_old_logs
    rm_proff_temp
    get_version
    gem_update
    make_diploy
elif [ "$1" == "$site_test" ]
then
    git_sub_update
    clean_old_logs
    rm_proff_temp
    #get_version
    #gem_update
    site_build
    run_htmlproof
elif [ "$1" == "$site_run" ]
then
   git_sub_update
   clean_old_logs
   rm_proff_temp
   #get_version
   #gem_update
   site_run
else
   echo "    Error in usage ..."
   echo "    ./build < -t | -r | -u> "
   echo "    "
   exit 1
fi
      
