#!/bin/bash

# this is test

if [ -f ./.debug ]
then
        run_cmd_debug=1
else
        run_cmd_debug=0
fi

WORKSPACE=$(pwd)
COMMIT_TIME=$(date +"%m-%d-%Y-%H:%M")
base_script=${0}

COMMIT_MSG=$1
if [ -z "$COMMIT_MSG" ]; then
	COMMIT_MSG="Updated-$COMMIT_TIME"
fi

is_git=0

function exit_process()
{
    # hack
    git submodule foreach git pull origin master
    echo "Exiting ..."
    clean_old_logs
    rm_proff_temp
}

if [ -f _toolScripts/bash_func ]; then
	. _toolScripts/bash_func
else
	echo "Error on _toolScripts/bash_func ..."
fi


### MAIN ###
check_git
git_sub_update
link_draft

clean_old_logs

#get_version
#gem_update
run_site_dyna

site_build
make_diploy

clean_old_logs

check_new
git_commit
git_push

clean_old_logs

### END ###

